ActiveBlendedStudy/ActiveBlendedStudy/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOL;
using BLL;
using ActiveBlendedStudy.Filters;

namespace ActiveBlendedStudy.Controllers
{
    [SessionAuthorize]
    public class QuizController : Controller
    {
        /**********************************************************************/
        // Instance Variables
        /**********************************************************************/

        private QuizManager quizManager;

        /// <summary>
        /// Hold the current course Id. Will be read from the session.
        /// </summary>
        private int courseId;

        /// <summary>
        /// Hold the current schedule Id. Will be read from the session.
        /// </summary>
        private int scheduleId;

        /// <summary>
        /// Hold the current user Id. Will be read from the session.
        /// </summary>
        private int userId;

        /**********************************************************************/
        // Constructors
        /**********************************************************************/
        public QuizController()
        {
            quizManager = new QuizManager();

        }

        /**********************************************************************/
        // Public Methods / Actions
        /**********************************************************************/

        /**
        * Methods for Quiz!!
        */

        // GET: Quiz
        public ActionResult Index()
        {
            GetValuesFromSession();
            ViewBag.IsCurrentSchedule = false;
            if (new ScheduleManager().IsScheduleTheLatest(scheduleId))
            {
                ViewBag.IsCurrentSchedule = true;
            }
            List<Quiz> quizs = (quizManager.GetAllQuiz(scheduleId, courseId).ToList());
            return View(quizs);
        }

        // GET: Quiz/Create
        [SessionAuthorize(role = "staff")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quiz/Create
        [HttpPost]
        [SessionAuthorize(role = "staff")]
        public ActionResult Create(Quiz newQuiz)
        {
            GetValuesFromSession();
            newQuiz.Schedule = new ScheduleManager().GetScheduleById(scheduleId);
            newQuiz.User = new LoginManager().GetUser(userId);
            newQuiz.Course = new CourseManager().GetCourse(courseId);
            quizManager.CreateNewQuiz(newQuiz);
            return RedirectToAction("Index");
        }

        // GET: Quiz/Delete/5
        [SessionAuthorize(role = "staff")]
        public ActionResult Delete(int id)
        {
            if (quizManager.DeleteQuizWithID(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return Content("PROBLEM WITH DELETING QUIZ");
            }
        }

        /// <summary>
        /// Action to be performed when a particular quiz is selected. 
        /// Depending on the type of user, the respective page is navigated.
        /// </summary>
        /// <param name="id">The quiz id that was selected.</param>
        /// <returns>The respective View depending on the user.</returns>
        public ActionResult QuizSelected(int id)
        {
            GetValuesFromSession();
            User currentUser = new LoginManager().GetUser(userId);
            if (currentUser.Role.ToUpper() == "STAFF")
            {
                return RedirectToAction("QuizDetails", new { id = id });
            }
            else
            {
                return RedirectToAction("AttemptQuiz", new { id = id });
            }
        }

        /**
        * Methods for Quiz Question!!
        */

        /// <summary>
        /// This will enlist all the questions present in a quiz.
        /// Essentially this is meant for viewing the questions in a quiz by the STAFF member.
        /// </summary>
        /// <param name="id">The quiz id for which the questions needs to be displayed.</param>
        /// <returns>View displaying all the questions.</returns>
        public ActionResult QuizDetails(int id)
        {
            GetValuesFromSession();
            ViewBag.IsCurrentSchedule = false;
            if (new ScheduleManager().IsScheduleTheLatest(scheduleId))
            {
                ViewBag.IsCurrentSchedule = true;
            }
            Quiz quiz = quizManager.getQuizById(id);
            ViewBag.CurrentQuizId = id;
            return View(quiz.Questions);
        }

        /// <summary>
        /// Create a new question in a quiz
        /// </summary>
        /// <param name="quizId"> The attached quiz ID.</param>
        /// <returns></returns>
        [SessionAuthorize(role = "staff")]
        public ActionResult CreateNewQuestion(int quizId)
        {
            ViewBag.CurrentQuizId = quizId;
            return View();
        }

        /// <summary>
        /// Adds a new question to the quizID that was passed as a parameter.
        /// </summary>
        /// <param name="quizId">The quiz ID to which the question needs to be added.</param>
        /// <param name="collection">The form collection containing all the values submitted by the user.</param>
        /// <returns>Back to the list of questions view.</returns>
        [HttpPost]
        [SessionAuthorize(role = "staff")]
        public ActionResult CreateNewQuestion(int quizId, FormCollection collection)
        {
            GetValuesFromSession();
            Quiz_Question question = GetQuestionFromCollection(collection);
            question.Quiz = quizManager.getQuizById(quizId);
            question.User = new LoginManager().GetUser(userId);
            quizManager.AddQuizQuestion(question);
            return RedirectToAction("QuizDetails", new { id = quizId });
        }

        [SessionAuthorize(role = "staff")]
        public ActionResult EditQuizQuestion(int id)
        {
            Quiz_Question question = quizManager.getQuestionById(id);
            return View(question);
        }

        [HttpPost]
        [SessionAuthorize(role = "staff")]
        public ActionResult EditQuizQuestion(FormCollection collection)
        {
            GetValuesFromSession();
            Quiz_Question question = GetQuestionFromCollection(collection);
            int questionId = int.Parse(collection["Quiz_Question_ID"]);
            question.Quiz_Question_ID = questionId;
            question.Quiz = quizManager.getQuestionById(questionId).Quiz;
            question.User = new LoginManager().GetUser(userId);
            quizManager.UpdateQuizQuestion(question);
            return RedirectToAction("QuizDetails", new { id = question.Quiz.Quiz_ID });
        }

        [SessionAuthorize(role = "staff")]
        public ActionResult DeleteQuestion(int id)
        {
            Quiz_Question question = quizManager.getQuestionById(id);
            int quizID = question.Quiz.Quiz_ID;
            // Delete the question from DB.
            quizManager.DeleteQuizQuestion(question.Quiz_Question_ID);
            return RedirectToAction("QuizDetails", new { id = quizID });
        }


        /// <summary>
        /// Allow the current user to attempt the quiz. 
        /// The view returned will allows the user to navigate through all the questions and submit the answers for each.
        /// </summary>
        /// <param name="id">The quiz id the current user is attempting.</param>
        /// <returns>The view which will allow the user to attempt the quiz.</returns>
        [SessionAuthorize(role = "student")]
        public ActionResult AttemptQuiz(int id)
        {
            ViewBag.HideSubmitButton = false;
            if (quizManager.IsEligibleToAttendQuiz(id, int.Parse(Session["User_ID"].ToString())))
            {
                Quiz quiz = quizManager.getQuizById(id);
                if(quiz.Questions.Count == 0)
                {
                    ViewBag.HideSubmitButton = true;
                }
                return View(quiz);
            }
            else
            {
                ViewBag.HideSubmitButton = true;
                return View();
            }
        }

        /// <summary>
        /// Get the view for a particular question
        /// </summary>
        /// <returns></returns>
        public ActionResult GetQuizQuestion(Quiz quiz)
        {
            if (quiz.Questions.Count() > 0)
            {
                // Show the first question by default
                Quiz_Question question = sortQuestions(quiz.Questions)[0];
                return PartialView(viewName: "_GetQuizQuestion", model: question);
            }
            return Content("NO QUESTIONS FOUND!!");
        }

        /// <summary>
        /// Collect data for an answered quiz question.
        /// </summary>
        /// <returns>Also return the view for the next question.</returns>
        [HttpPost]
        public ActionResult GetQuizQuestion(int quizId, FormCollection collection)
        {
            GetValuesFromSession();
            ViewBag.HideSubmitButton = false;
            int currentQuestionId = int.Parse(collection["Quiz_Question_ID"]);
            Dictionary<int, string> answerDict;
            if (Session["Quiz_Answers"] != null)
            {
                // Add value to hashmap
                answerDict = Session["Quiz_Answers"] as Dictionary<int, string>;
            }
            else
            {
                // Create new hashmap
                answerDict = new Dictionary<int, string>();
            }
            // Set the values in session

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/AttemptQuiz.cshtml
@model BOL.Quiz
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@{
    ViewBag.Title = "AttemptQuiz";
}

<script type="text/javascript">
function hideSubmitButtonAfterQuizCompletion(){
    document.getElementById("submit").style.display = "none";
    document.getElementById("quizQuestion").innerHTML = "Quiz Submitted!";
}
</script>

<h2>AttemptQuiz</h2>
@if (Model != null)
{
    <div>
        @using (Ajax.BeginForm("GetQuizQuestion", "Quiz", new { quizId = Model.Quiz_ID }, new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "quizQuestion"
        }))
        {
            <div id="quizQuestion">
                @{Html.RenderAction("GetQuizQuestion", "Quiz", new { quiz = Model });}
            </div>
                    if (!(ViewBag.HideSubmitButton.ToString().ToLower() == "true"))
                    {
                        <input id="submit" type="submit" value="Submit" />
                        }
                    }
    </div>
                    }
                    else
                    {
                        <div>You have already submitted the Quiz!</div>
                    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/Create.cshtml

@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Quiz

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Quiz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/CreateNewQuestion.cshtml

@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Quiz_Question

@{
    ViewBag.Title = "CreateNewQuestion";
}

<h2>CreateNewQuestion</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz_Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/CreateQuestions.cshtml

@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Quiz_Question

@{
    ViewBag.Title = "CreateQuestions";
}

<h2>CreateQuestions</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz_Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Quiz_Question_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add More Questions" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/EditQuizQuestion.cshtml
@model BOL.Quiz_Question

@{
    ViewBag.Title = "EditQuizQuestion";
}

<h2>EditQuizQuestion</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quiz_Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Quiz_Question_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option_4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option_4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Option_4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/EditQuiz_Questions.cshtml

@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Quiz


@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">

        <tr>

            <th>
                <h3>Question</h3>
            </th>
            <th>
                <h3>Option_1</h3>

            </th>
            <th>
                <h3>Option 2</h3>

            </th>
            <th>
                <h3>Option 3</h3>
            </th>
            <th>
                <h3>Option 4</h3>
            </th>
            <th>
                <h3>Answer</h3>

            </th>

            <th></th>
        </tr>

        @for (int i = 0; i < Model.Questions.Count; i++)
                {
            <tr>


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(modelItem => Model.Questions[i].Quiz_Question_ID)

                <td>
                    @Html.EditorFor(modelItem => Model.Questions[i].Question, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(modelItem => Model.Questions[i].Question, "", new { @class = "text-danger" })
                </td>



                <td>
                    @Html.EditorFor(modelItem => Model.Questions[i].Option_1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(modelItem => Model.Questions[i].Option_1, "", new { @class = "text-danger" })
                </td>

                <td>
                    @Html.EditorFor(modelItem => Model.Questions[i].Option_2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(modelItem => Model.Questions[i].Option_2, "", new { @class = "text-danger" })

                </td>

                <td>
                    @Html.EditorFor(modelItem => Model.Questions[i].Option_3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(modelItem => Model.Questions[i].Option_3, "", new { @class = "text-danger" })
                </td>


                <td>
                    @Html.EditorFor(modelItem => Model.Questions[i].Option_4, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(modelItem => Model.Questions[i].Option_4, "", new { @class = "text-danger" })
                </td>

                <td>
                    @Html.EditorFor(modelItem => Model.Questions[i].Answer, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(modelItem => Model.Questions[i].Answer, "", new { @class = "text-danger" })
                </td>
            </tr>
        }
    </table>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/Index.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model IEnumerable<BOL.Quiz>

@{
    ViewBag.Title = "Index";
}

<script>
    function showAlertForRepostConfirmation(id) {
        if (confirm('Do you want to repost this quiz for the current schedule?')) {
            window.location.href = '@Url.Action("RepostQuiz", "Quiz")/' + id;
        } else {
            // Do nothing!
        }
    }
</script>

<h2>Quiz</h2>
@{
    if (Session["Role"].ToString().ToUpper().Equals("STAFF"))
    {
        if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
        {
            <p>
                @Html.ActionLink("Create New Quiz", "Create")
            </p>
        }
    }
}
<table class="table table-bordered table-striped">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "QuizSelected", new { id = item.Quiz_ID })
            </td>
            @if (Session["Role"].ToString().ToUpper().Equals("STAFF"))
            {
                if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
                {
                    <td>
                        @Html.ActionLink("Stats", "Statistics", new { id = item.Quiz_ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Quiz_ID })
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Stats", "Statistics", new { id = item.Quiz_ID }) |
                        <a onclick="showAlertForRepostConfirmation('@item.Quiz_ID');">Repost</a>
                    </td>
                }
            }
</tr>
            }

</table>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/QuizDetails.cshtml
@model IEnumerable<BOL.Quiz_Question>
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@{
    ViewBag.Title = "QuizDetails";
}

<script>
    function showAlertForDeleteConfirmation(id) {
        if (confirm('Do you want to delete this question?')) {
            window.location.href = '@Url.Action("DeleteQuestion", "Quiz")/' + id;
        } else {
            // Do nothing!
        }
    }
</script>

<h2>QuizDetails</h2>
@if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
{
    <p>
        @Html.ActionLink("Create New", "CreateNewQuestion", new { quizId = ViewBag.CurrentQuizId })
    </p>
}

<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Question)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Option_1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Option_2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Option_3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Option_4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Answer)
        </th>

        @if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
        {
            <th></th>
        }
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Question)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Option_1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Option_2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Option_3)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Option_4)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Answer)
        </td>
        @if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
        {
            <td>
                @Html.ActionLink("Edit", "EditQuizQuestion", new { id = item.Quiz_Question_ID }) |
                <a onclick="showAlertForDeleteConfirmation('@item.Quiz_Question_ID');">Delete</a>
            </td>
        }
    </tr>
}

</table>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/RepostQuiz.cshtml
@model List<Object> 

@{ 
    BOL.Quiz quiz = Model.ElementAt(0) as BOL.Quiz;
    BOL.Schedule schedule= Model.ElementAt(1) as BOL.Schedule;
}

@{
    ViewBag.Title = "RepostQuiz";
}
<h2>RepostQuiz</h2>

<h5> You're about to repost a Quiz with <br />TITLE: @quiz.Name <br /> COURSE: @quiz.Course.Name <br /> SCHEDULE: @schedule.Schedule_Name <br /> </h5>

@using (Html.BeginForm("RepostQuiz", "Quiz", new { id = quiz.Quiz_ID, user = Session["User_ID"].ToString(), FormMethod.Post }))
{
    <input type="submit" value="Confirm Repost"/>
}

ActiveBlendedStudy/ActiveBlendedStudy/Views/Quiz/_GetQuizQuestion.cshtml
@model BOL.Quiz_Question

<fieldset class="scheduler-border">
    @Html.HiddenFor(model => model.Quiz_Question_ID, new { questionId = Model.Quiz_Question_ID })
    <legend class="scheduler-border">@Model.Question</legend>
    <div class="radio">
        <label><input type="radio" name="answer" value="Option_1" required>@Model.Option_1</label>
    </div>
    <div class="radio">
        <label><input type="radio" name="answer" value="Option_2">@Model.Option_2</label>
    </div>
    <div class="radio">
        <label><input type="radio" name="answer" value="Option_3">@Model.Option_3</label>
    </div>
    <div class="radio">
        <label><input type="radio" name="answer" value="Option_4">@Model.Option_4</label>
    </div>
</fieldset>