ActiveBlendedStudy/ActiveBlendedStudy/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOL;
using BLL;
using ActiveBlendedStudy.Filters;

namespace ActiveBlendedStudy.Controllers
{
    [SessionAuthorize]
    public class ForumController : Controller
    {
        /**********************************************************************/
        // Instance Variables
        /**********************************************************************/

        /// <summary>
        /// Hold the current course Id. Will be read from the session.
        /// </summary>
        private int courseId;

        /// <summary>
        /// Hold the current schedule Id. Will be read from the session.
        /// </summary>
        private int scheduleId;

        /// <summary>
        /// Hold the current user Id. Will be read from the session.
        /// </summary>
        private int userId;

        /// <summary>
        /// The forum manager object that will allow the controller to communicate with dB.
        /// </summary>
        private ForumManager forumManager;

        /**********************************************************************/
        // Constructors
        /**********************************************************************/
        public ForumController()
        {
            forumManager = new ForumManager();
        }

        /**********************************************************************/
        // Public Methods
        /**********************************************************************/
        // GET: Forum

        public ActionResult Index()
        {
            GetValuesFromSession();
            ViewBag.IsCurrentSchedule = false;
            if (new ScheduleManager().IsScheduleTheLatest(scheduleId))
            {
                ViewBag.IsCurrentSchedule = true;
            }
            return View(forumManager.GetAllForums(scheduleId, courseId).ToList());
        }

        // GET: Forum/Details/5
        public ActionResult Details(int id)
        {
            return RedirectToAction("Index", "ForumPosts");
        }

        // GET: Forum/Create
        [SessionAuthorize(role = "staff")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Forum/Create
        [SessionAuthorize(role = "staff")]
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                GetValuesFromSession();
                Forum forum = GetForumFromCollection(collection);
                forum.Schedule = new ScheduleManager().GetScheduleById(scheduleId);
                forum.User = new LoginManager().GetUser(userId);
                forum.Course = new CourseManager().GetCourse(courseId);
                forumManager.AddForum(forum);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [SessionAuthorize(role = "staff")]
        // GET: Forum/Edit/5
        public ActionResult Edit(int id)
        {
            Forum forumToEdit = forumManager.GetForum(id);
            return View(forumToEdit);
        }

        // POST: Forum/Edit/5
        [HttpPost]
        [SessionAuthorize(role = "staff")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                GetValuesFromSession();
                // Create the material object to update
                Forum updatedForum = GetForumFromCollection(collection);
                updatedForum.Forum_ID = id;
                updatedForum.Schedule = new ScheduleManager().GetScheduleById(scheduleId);
                updatedForum.User = new LoginManager().GetUser(userId);
                updatedForum.Course = new CourseManager().GetCourse(courseId);

                // Now save the same
                forumManager.UpdateForum(updatedForum);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Forum/Delete/5
        [SessionAuthorize(role = "staff")]
        public ActionResult Delete(int id)
        {
            Forum forumToDelete = forumManager.GetForum(id);
            return View(forumToDelete);
        }

        // POST: Forum/Delete/5
        [SessionAuthorize(role = "staff")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                forumManager.DeleteForum(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// This will be display all the answers related to a particular forum topic.
        /// </summary>
        /// <returns>View displaying all the forum answers for a particular forum topic</returns>
        public ActionResult DisplayForumPosts(int id)
        {
            ViewBag.Title = forumManager.GetForum(id).Topic;
            ViewBag.Id = id;
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public PartialViewResult PostForumAnswer(int id, string newPost)
        {
            if (newPost.Length > 0)
            {
                GetValuesFromSession();
                LoginManager loginManager = new LoginManager();

                Forum_Answer forumAnswer = new Forum_Answer();
                forumAnswer.Forum = forumManager.GetForum(id);
                forumAnswer.User = loginManager.GetUser(userId);
                forumAnswer.Answer = newPost;
                // We need to insert here
                forumManager.AddForumPost(forumAnswer);
            }
            List<Forum_Answer> forum_Answers = forumManager.GetAllForumAnswers(id).ToList();
            return PartialView(viewName: "PostForumAnswer", model: forum_Answers);
        }

        /**********************************************************************/
        // Private Methods
        /**********************************************************************/
        /// <summary>
        /// Method to get the forum object from the FormCollection
        /// </summary>
        /// <param name="collection">The collection from which the material object needs to be retrieved.</param>
        /// <returns></returns>
        private Forum GetForumFromCollection(FormCollection collection)
        {
            Forum retrievedForum = new Forum();
            retrievedForum.Topic = collection["Topic"];
            return retrievedForum;
        }

        /// <summary>
        /// Method to get the various values from Session.
        /// </summary>
        private void GetValuesFromSession()
        {
            scheduleId = int.Parse(Session["Schedule_ID"].ToString());
            courseId = int.Parse(Session["Course_ID"].ToString());
            userId = int.Parse(Session["User_ID"].ToString());
        }

    }
}

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/Create.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Forum

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Forum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     
        <div class="form-group">
            @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/Delete.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Forum

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Forum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Topic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Topic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/Details.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model IEnumerable<BOL.Forum_Answer>

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Answer)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Answer)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Forum_Answer_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Forum_Answer_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Forum_Answer_ID })
        </td>
    </tr>
}

</table>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/DisplayForumPosts.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

<script>
    function clearBox()
    {
        document.getElementById("account").value = "";
    }
</script>


<div id="table">
    @Html.Action("PostForumAnswer", new {id = ViewBag.Id, newPost = "" })
</div>

<div>
    @using (Ajax.BeginForm("PostForumAnswer", "Forum", new { id = ViewBag.Id },new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "table"
    }

    ))
    {
        <input id="account" type="text" name="newPost" />
        <input type="submit" value="Comment" onmouseout="clearBox()"/>
    }
</div>
<br />
<br />

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/Edit.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model BOL.Forum

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Forum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Forum_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Topic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Topic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/Index.cshtml
@{
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

@model IEnumerable<BOL.Forum>


<h2>Forum</h2>
@{
    if (Session["Role"].ToString().ToUpper().Equals("STAFF"))
    {
        if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
        {
        <p>
            @Html.ActionLink("Create New Forum", "Create")
        </p>
            }
        }
    }
<table class="table table-bordered table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Topic)
        </th>
        @if (Session["Role"].ToString().ToUpper().Equals("STAFF"))
        {
            if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
            {
            <th></th>
            }
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Topic, "DisplayForumPosts", new { id = item.Forum_ID })
            </td>
            @if (Session["Role"].ToString().ToUpper().Equals("STAFF"))
            {
                if (ViewBag.IsCurrentSchedule.ToString().ToLower().Equals("true"))
                {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Forum_ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Forum_ID })
                </td>
                }
            }
        </tr>
    }

</table>

ActiveBlendedStudy/ActiveBlendedStudy/Views/Forum/PostForumAnswer.cshtml
@model IEnumerable<BOL.Forum_Answer>

<table class="table table-bordered table-striped">
    <tr>
        <th>
            Post
        </th>
        <th>
           User
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Answer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
        </tr>
    }

</table>